export const PREPARE_FETCH_EARTHQUAKES = 'PREPARE_FETCH_EARTHQUAKES';
export const FETCH_EARTHQUAKES_SUCCESS = 'FETCH_EARTHQUAKES_SUCCESS';
export const FETCH_EARTHQUAKES_FAILED = 'FETCH_EARTHQUAKES_FAILED';
